version: '3.8'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  db:
    image: "postgres:13"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: db
      POSTGRES_MAX_CONNECTIONS: 200
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

volumes:
  db_data:
